// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export class AwsAccount extends pulumi.CustomResource {
    /**
     * Get an existing AwsAccount resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AwsAccountState, opts?: pulumi.CustomResourceOptions): AwsAccount {
        return new AwsAccount(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'controltower:index/awsAccount:AwsAccount';

    /**
     * Returns true if the given object is an instance of AwsAccount.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AwsAccount {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AwsAccount.__pulumiType;
    }

    /**
     * ID of the AWS account.
     */
    public /*out*/ readonly accountId!: pulumi.Output<string>;
    /**
     * Root email of the account.
     */
    public readonly email!: pulumi.Output<string>;
    /**
     * Name of the account.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Name of the Organizational Unit under which the account resides.
     */
    public readonly organizationalUnit!: pulumi.Output<string>;
    /**
     * Name of the service catalog product that is provisioned. Defaults to a slugified version of the account name.
     */
    public readonly provisionedProductName!: pulumi.Output<string>;
    /**
     * Assigned SSO user settings.
     */
    public readonly sso!: pulumi.Output<outputs.AwsAccountSso>;
    /**
     * Key-value map of resource tags for the account.
     */
    public readonly tags!: pulumi.Output<{[key: string]: string} | undefined>;

    /**
     * Create a AwsAccount resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AwsAccountArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AwsAccountArgs | AwsAccountState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AwsAccountState | undefined;
            inputs["accountId"] = state ? state.accountId : undefined;
            inputs["email"] = state ? state.email : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["organizationalUnit"] = state ? state.organizationalUnit : undefined;
            inputs["provisionedProductName"] = state ? state.provisionedProductName : undefined;
            inputs["sso"] = state ? state.sso : undefined;
            inputs["tags"] = state ? state.tags : undefined;
        } else {
            const args = argsOrState as AwsAccountArgs | undefined;
            if ((!args || args.email === undefined) && !opts.urn) {
                throw new Error("Missing required property 'email'");
            }
            if ((!args || args.organizationalUnit === undefined) && !opts.urn) {
                throw new Error("Missing required property 'organizationalUnit'");
            }
            if ((!args || args.sso === undefined) && !opts.urn) {
                throw new Error("Missing required property 'sso'");
            }
            inputs["email"] = args ? args.email : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["organizationalUnit"] = args ? args.organizationalUnit : undefined;
            inputs["provisionedProductName"] = args ? args.provisionedProductName : undefined;
            inputs["sso"] = args ? args.sso : undefined;
            inputs["tags"] = args ? args.tags : undefined;
            inputs["accountId"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(AwsAccount.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AwsAccount resources.
 */
export interface AwsAccountState {
    /**
     * ID of the AWS account.
     */
    accountId?: pulumi.Input<string>;
    /**
     * Root email of the account.
     */
    email?: pulumi.Input<string>;
    /**
     * Name of the account.
     */
    name?: pulumi.Input<string>;
    /**
     * Name of the Organizational Unit under which the account resides.
     */
    organizationalUnit?: pulumi.Input<string>;
    /**
     * Name of the service catalog product that is provisioned. Defaults to a slugified version of the account name.
     */
    provisionedProductName?: pulumi.Input<string>;
    /**
     * Assigned SSO user settings.
     */
    sso?: pulumi.Input<inputs.AwsAccountSso>;
    /**
     * Key-value map of resource tags for the account.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}

/**
 * The set of arguments for constructing a AwsAccount resource.
 */
export interface AwsAccountArgs {
    /**
     * Root email of the account.
     */
    email: pulumi.Input<string>;
    /**
     * Name of the account.
     */
    name?: pulumi.Input<string>;
    /**
     * Name of the Organizational Unit under which the account resides.
     */
    organizationalUnit: pulumi.Input<string>;
    /**
     * Name of the service catalog product that is provisioned. Defaults to a slugified version of the account name.
     */
    provisionedProductName?: pulumi.Input<string>;
    /**
     * Assigned SSO user settings.
     */
    sso: pulumi.Input<inputs.AwsAccountSso>;
    /**
     * Key-value map of resource tags for the account.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}
