// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * The provider type for the controltower package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'controltower';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Provider.__pulumiType;
    }

    /**
     * This is the AWS access key. It must be provided, but it can also be sourced from the `AWS_ACCESS_KEY_ID` environment
     * variable, or via a shared credentials file if `profile` is specified.
     */
    public readonly accessKey!: pulumi.Output<string | undefined>;
    /**
     * This is the AWS profile name as set in the shared credentials file.
     */
    public readonly profile!: pulumi.Output<string | undefined>;
    /**
     * This is the AWS region. It must be provided, but it can also be sourced from the `AWS_DEFAULT_REGION` environment
     * variables, or via a shared credentials file if `profile` is specified.
     */
    public readonly region!: pulumi.Output<string>;
    /**
     * This is the AWS secret key. It must be provided, but it can also be sourced from the `AWS_SECRET_ACCESS_KEY` environment
     * variable, or via a shared credentials file if `profile` is specified.
     */
    public readonly secretKey!: pulumi.Output<string | undefined>;
    /**
     * This is the path to the shared credentials file. If this is not set and a profile is specified, `~/.aws/credentials`
     * will be used.
     */
    public readonly sharedCredentialsFile!: pulumi.Output<string | undefined>;
    /**
     * Session token for validating temporary credentials. Typically provided after successful identity federation or
     * Multi-Factor Authentication (MFA) login. With MFA login, this is the session token provided afterward, not the 6 digit
     * MFA code used to get temporary credentials. It can also be sourced from the `AWS_SESSION_TOKEN` environment variable.
     */
    public readonly token!: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            if ((!args || args.region === undefined) && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            inputs["accessKey"] = args ? args.accessKey : undefined;
            inputs["assumeRole"] = pulumi.output(args ? args.assumeRole : undefined).apply(JSON.stringify);
            inputs["maxRetries"] = pulumi.output(args ? args.maxRetries : undefined).apply(JSON.stringify);
            inputs["profile"] = args ? args.profile : undefined;
            inputs["region"] = args ? args.region : undefined;
            inputs["secretKey"] = args ? args.secretKey : undefined;
            inputs["sharedCredentialsFile"] = args ? args.sharedCredentialsFile : undefined;
            inputs["skipCredentialsValidation"] = pulumi.output(args ? args.skipCredentialsValidation : undefined).apply(JSON.stringify);
            inputs["skipMetadataApiCheck"] = pulumi.output(args ? args.skipMetadataApiCheck : undefined).apply(JSON.stringify);
            inputs["skipRequestingAccountId"] = pulumi.output(args ? args.skipRequestingAccountId : undefined).apply(JSON.stringify);
            inputs["token"] = args ? args.token : undefined;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(Provider.__pulumiType, name, inputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * This is the AWS access key. It must be provided, but it can also be sourced from the `AWS_ACCESS_KEY_ID` environment
     * variable, or via a shared credentials file if `profile` is specified.
     */
    accessKey?: pulumi.Input<string>;
    /**
     * Settings for making use of the AWS Assume Role functionality.
     */
    assumeRole?: pulumi.Input<inputs.ProviderAssumeRole>;
    /**
     * This is the maximum number of times an API call is retried, in the case where requests are being throttled or
     * experiencing transient failures. The delay between the subsequent API calls increases exponentially. If omitted, the
     * default value is `25`.
     */
    maxRetries?: pulumi.Input<number>;
    /**
     * This is the AWS profile name as set in the shared credentials file.
     */
    profile?: pulumi.Input<string>;
    /**
     * This is the AWS region. It must be provided, but it can also be sourced from the `AWS_DEFAULT_REGION` environment
     * variables, or via a shared credentials file if `profile` is specified.
     */
    region: pulumi.Input<string>;
    /**
     * This is the AWS secret key. It must be provided, but it can also be sourced from the `AWS_SECRET_ACCESS_KEY` environment
     * variable, or via a shared credentials file if `profile` is specified.
     */
    secretKey?: pulumi.Input<string>;
    /**
     * This is the path to the shared credentials file. If this is not set and a profile is specified, `~/.aws/credentials`
     * will be used.
     */
    sharedCredentialsFile?: pulumi.Input<string>;
    /**
     * Skip the credentials validation via the STS API. Useful for AWS API implementations that do not have STS available or
     * implemented.
     */
    skipCredentialsValidation?: pulumi.Input<boolean>;
    /**
     * Skip the AWS Metadata API check. Useful for AWS API implementations that do not have a metadata API endpoint. Setting to
     * `true` prevents Terraform from authenticating via the Metadata API. You may need to use other authentication methods
     * like static credentials, configuration variables, or environment variables.
     */
    skipMetadataApiCheck?: pulumi.Input<boolean>;
    /**
     * Skip requesting the account ID. Useful for AWS API implementations that do not have the IAM, STS API, or metadata API.
     */
    skipRequestingAccountId?: pulumi.Input<boolean>;
    /**
     * Session token for validating temporary credentials. Typically provided after successful identity federation or
     * Multi-Factor Authentication (MFA) login. With MFA login, this is the session token provided afterward, not the 6 digit
     * MFA code used to get temporary credentials. It can also be sourced from the `AWS_SESSION_TOKEN` environment variable.
     */
    token?: pulumi.Input<string>;
}
